---
- name: Check for the installed status file
  stat:
    path: "{{ linuxfabrik_monitoring_plugins_dest_path }}/linuxfabrik-monitoring-plugins.installed"
  register: installed_status_file

- set_fact:
    linuxfabrik_monitoring_plugins_installed: true
  when: installed_status_file.stat.exists
