---
- name: Check for the installed status file
  stat:
    path: /etc/icinga2/.linuxfabrik-monitoring-plugins.installed
  register: installed_status_file

- set_fact:
    linuxfabrik_monitoring_plugins_installed: true
  when: installed_status_file.stat.exists
