---
- name: Download Linuxfabrik Monitoring Plugins Icons
  get_url:
    url: "{{ linuxfabrik_monitoring_plugins_icons_url }}"
    dest: /tmp/linuxfabrik_monitoring_plugins_icons.tar
    owner: "{{ linuxfabrik_monitoring_plugins_user }}"
    group: "{{ linuxfabrik_monitoring_plugins_group }}"
    force: true

- name: Create the temporary directory
  file:
    path: /tmp/linuxfabrik_monitoring_plugins_icons
    state: directory
    owner: "{{ linuxfabrik_monitoring_plugins_user }}"
    group: "{{ linuxfabrik_monitoring_plugins_group }}"

- name: Extract the downloaded archive
  unarchive:
    src: /tmp/linuxfabrik_monitoring_plugins_icons.tar
    dest: /tmp/linuxfabrik_monitoring_plugins_icons
    remote_src: true
    owner: "{{ linuxfabrik_monitoring_plugins_user }}"
    group: "{{ linuxfabrik_monitoring_plugins_group }}" 

- name: Copy icons
  shell: "cp -a /tmp/linuxfabrik_monitoring_plugins_icons/* {{ linuxfabrik_monitoring_plugins_icingaweb2_icons_dir_path }}/"

- name: Remove the temporary directory
  shell: rm -rf /tmp/linuxfabrik_monitoring_plugins_icons

- name: Remove the downloaded archive
  file:
    path: /tmp/linuxfabrik_monitoring_plugins_icons.tar
    state: absent
