---
- name: Unsupported install method
  ansible.builtin.fail:
    msg: "Unsupported install method: {{ linuxfabrik_monitoring_plugins_install_method }}"
  when: linuxfabrik_monitoring_plugins_install_method not in ['package', 'tar']

- name: Install LinuxFabrik Monitoring Plugins using APT
  ansible.builtin.include_tasks: install-Linux-Debian.yml
  when:
    - ansible_os_family in ['Debian', 'Ubuntu']
    - linuxfabrik_monitoring_plugins_install_method == "package"

- name: Install LinuxFabrik Monitoring Plugins using TAR
  ansible.builtin.include_tasks: install-Linux-tar.yml
  when: linuxfabrik_monitoring_plugins_install_method == "tar"

- name: Define the installation dir constant
  ansible.builtin.lineinfile:
    path: /etc/icinga2/constants.conf
    line: "const LinuxfabrikMonitoringPluginsDir = \"{{ linuxfabrik_monitoring_plugins_dest_path }}\""
  notify: Reload Icinga2

- name: Copy the command definitions file
  ansible.builtin.template:
    src: linuxfabrik-commands-linux.conf.j2
    dest: "{{ linuxfabrik_monitoring_plugins_commands_dest_path }}/linuxfabrik-commands.conf"
    mode: "0644"
    owner: "{{ linuxfabrik_monitoring_plugins_user }}"
    group: "{{ linuxfabrik_monitoring_plugins_group }}"
  notify: Reload Icinga2

- name: Install Windows command definitions on Linux system
  ansible.builtin.template:
    src: linuxfabrik-commands-windows.conf.j2
    dest: "{{ linuxfabrik_monitoring_plugins_commands_dest_path }}/windows-linuxfabrik-commands.conf"
    mode: "0644"
    owner: "{{ linuxfabrik_monitoring_plugins_user }}"
    group: "{{ linuxfabrik_monitoring_plugins_group }}"
  vars:
    linuxfabrik_monitoring_plugins_dest_path: 'C:\Program Files\ICINGA2\linuxfabrik'
  when: linuxfabrik_monitoring_plugins_install_windows_commands_on_linux
  notify: Reload Icinga2

- name: Copy the template definitions file
  ansible.builtin.template:
    src: linuxfabrik-templates.conf.j2
    dest: "{{ linuxfabrik_monitoring_plugins_commands_dest_path }}/linuxfabrik-templates.conf"
    mode: "0644"
    owner: "{{ linuxfabrik_monitoring_plugins_user }}"
    group: "{{ linuxfabrik_monitoring_plugins_group }}"
  notify: Reload Icinga2

- name: Configure sudo
  ansible.builtin.template:
    src: linuxfabrik-sudoers.j2
    dest: /etc/sudoers.d/linuxfabrik-monitoring-plugins
    mode: "0644"
    owner: root
    group: root

- name: Create the installed status file
  ansible.builtin.file:
    path: /etc/icinga2/.linuxfabrik-monitoring-plugins.installed
    state: touch
    mode: "0644"
    owner: "{{ linuxfabrik_monitoring_plugins_user }}"
    group: "{{ linuxfabrik_monitoring_plugins_group }}"
