---
- name: Remove existing installation if exists
  ansible.builtin.file:
    path: "{{ linuxfabrik_monitoring_plugins_dest_path }}"
    state: absent

- name: Install required packages
  ansible.builtin.package:
    name: "{{ linuxfabrik_monitoring_plugins_required_packages }}"
    state: present

- name: Install required PIP packages
  ansible.builtin.pip:
    name: "{{ linuxfabrik_monitoring_plugins_required_pip_packages }}"
    state: present
  environment:
    PIP_BREAK_SYSTEM_PACKAGES: 1

- name: Set the download file name
  ansible.builtin.set_fact:
    _linuxfabrik_monitoring_plugins_file: "{{ 'linuxfabrik-monitoring-plugins.tar' if linuxfabrik_monitoring_plugins_version == 'latest' else 'linuxfabrik-monitoring-plugins-' ~ linuxfabrik_monitoring_plugins_version ~ '.tar' }}"

- name: Set the download URL
  ansible.builtin.set_fact:
    _linuxfabrik_monitoring_plugins_url: "https://download.linuxfabrik.ch/monitoring-plugins/tar/{{ _linuxfabrik_monitoring_plugins_file }}"

- name: Download Linuxfabrik Monitoring Plugins
  ansible.builtin.get_url:
    url: "{{ linuxfabrik_monitoring_plugins_url }}"
    dest: /tmp/linuxfabrik_monitoring_plugins.tar
    owner: "{{ linuxfabrik_monitoring_plugins_user }}"
    group: "{{ linuxfabrik_monitoring_plugins_group }}"
    force: true
    mode: "0640"

- name: Create the temporary directory
  ansible.builtin.file:
    path: /tmp/linuxfabrik_monitoring_plugins
    state: directory
    mode: "0750"
    owner: "{{ linuxfabrik_monitoring_plugins_user }}"
    group: "{{ linuxfabrik_monitoring_plugins_group }}"

- name: Extract the downloaded archive
  ansible.builtin.unarchive:
    src: /tmp/linuxfabrik_monitoring_plugins.tar
    dest: /tmp/linuxfabrik_monitoring_plugins
    remote_src: true
    owner: "{{ linuxfabrik_monitoring_plugins_user }}"
    group: "{{ linuxfabrik_monitoring_plugins_group }}"

- name: Create the destination directory
  ansible.builtin.file:
    path: "{{ linuxfabrik_monitoring_plugins_dest_path }}"
    state: directory
    recurse: true
    owner: "{{ linuxfabrik_monitoring_plugins_user }}"
    group: "{{ linuxfabrik_monitoring_plugins_group }}"

- name: Copy plugins to the destination directory
  ansible.builtin.shell: "cp -a /tmp/linuxfabrik_monitoring_plugins/usr/lib64/nagios/plugins/* {{ linuxfabrik_monitoring_plugins_dest_path }}/"
  register: command
  changed_when: command.rc == 0

- name: Remove the temporary directory
  ansible.builtin.file:
    path: /tmp/linuxfabrik_monitoring_plugins
    state: absent

- name: Remove the downloaded archive
  ansible.builtin.file:
    path: /tmp/linuxfabrik_monitoring_plugins.tar
    state: absent

- name: Copy the command definitions file
  ansible.builtin.template:
    src: linuxfabrik-commands-linux.conf.j2
    dest: "{{ linuxfabrik_monitoring_plugins_commands_dest_path }}/linuxfabrik-commands.conf"
    mode: "0644"
    owner: "{{ linuxfabrik_monitoring_plugins_user }}"
    group: "{{ linuxfabrik_monitoring_plugins_group }}"
  notify: Reload Icinga2

- name: Install Windows command definitions on Linux system
  ansible.builtin.template:
    src: linuxfabrik-commands-windows.conf.j2
    dest: "{{ linuxfabrik_monitoring_plugins_commands_dest_path }}/windows-linuxfabrik-commands.conf"
    mode: "0644"
    owner: "{{ linuxfabrik_monitoring_plugins_user }}"
    group: "{{ linuxfabrik_monitoring_plugins_group }}"
  vars:
    linuxfabrik_monitoring_plugins_dest_path: 'C:\Program Files\ICINGA2\linuxfabrik'
  when: linuxfabrik_monitoring_plugins_install_windows_commands_on_linux
  notify: Reload Icinga2

- name: Copy the template definitions file
  ansible.builtin.template:
    src: linuxfabrik-templates.conf.j2
    dest: "{{ linuxfabrik_monitoring_plugins_commands_dest_path }}/linuxfabrik-templates.conf"
    mode: "0644"
    owner: "{{ linuxfabrik_monitoring_plugins_user }}"
    group: "{{ linuxfabrik_monitoring_plugins_group }}"
  notify: Reload Icinga2

- name: Configure sudo
  ansible.builtin.template:
    src: linuxfabrik-sudoers.j2
    dest: /etc/sudoers.d/linuxfabrik-monitoring-plugins
    mode: "0644"
    owner: root
    group: root

- name: Create the installed status file
  ansible.builtin.file:
    path: /etc/icinga2/.linuxfabrik-monitoring-plugins.installed
    state: touch
    mode: "0644"
    owner: "{{ linuxfabrik_monitoring_plugins_user }}"
    group: "{{ linuxfabrik_monitoring_plugins_group }}"
