---
- name: Install required packages
  package:
    name: "{{ linuxfabrik_monitoring_plugins_required_packages }}"
    state: present

- name: Install required PIP packages
  pip:
    name: "{{ linuxfabrik_monitoring_plugins_required_pip_packages }}"
    state: present

- name: Download Linuxfabrik Monitoring Plugins
  get_url:
    url: "{{ linuxfabrik_monitoring_plugins_url }}"
    dest: /tmp/linuxfabrik_monitoring_plugins.tar
    owner: "{{ linuxfabrik_monitoring_plugins_user }}"
    group: "{{ linuxfabrik_monitoring_plugins_group }}"
    force: true

- name: Create the temporary directory
  file:
    path: /tmp/linuxfabrik_monitoring_plugins
    state: directory
    owner: "{{ linuxfabrik_monitoring_plugins_user }}"
    group: "{{ linuxfabrik_monitoring_plugins_group }}"

- name: Extract the downloaded archive
  unarchive:
    src: /tmp/linuxfabrik_monitoring_plugins.tar
    dest: /tmp/linuxfabrik_monitoring_plugins
    remote_src: true
    owner: "{{ linuxfabrik_monitoring_plugins_user }}"
    group: "{{ linuxfabrik_monitoring_plugins_group }}"

- name: Create the destination directory
  file:
    path: "{{ linuxfabrik_monitoring_plugins_dest_path }}"
    state: directory
    recurse: true
    owner: "{{ linuxfabrik_monitoring_plugins_user }}"
    group: "{{ linuxfabrik_monitoring_plugins_group }}"    

- name: Copy plugins to the destination directory
  shell: "cp -a /tmp/linuxfabrik_monitoring_plugins/usr/lib64/nagios/plugins/* {{ linuxfabrik_monitoring_plugins_dest_path }}/"

- name: Remove the temporary directory
  shell: rm -rf /tmp/linuxfabrik_monitoring_plugins

- name: Remove the downloaded archive
  file:
    path: /tmp/linuxfabrik_monitoring_plugins.tar
    state: absent

- name: Create the command definitions destination directory
  file:
    path: "{{ linuxfabrik_monitoring_plugins_commands_dest_path }}"
    state: directory
    recurse: true
    owner: "{{ linuxfabrik_monitoring_plugins_user }}"
    group: "{{ linuxfabrik_monitoring_plugins_group }}"    

- name: Copy the command definitions files
  template:
    src: "{{ item }}"
    dest: "{{ linuxfabrik_monitoring_plugins_commands_dest_path }}/{{ item | basename | regex_replace('\\.j2$', '') }}"
  with_fileglob:
    - ../templates/plugin-commands-linux/*.j2
  notify: Reload Icinga2

- name: Configure sudo
  template:
    src: linuxfabrik-sudoers.j2
    dest: /etc/sudoers.d/linuxfabrik-monitoring-plugins

- name: Include the command definitions destination directory
  lineinfile:
    path: "{{ linuxfabrik_monitoring_plugins_icinga_conf_file }}"
    regexp: '^(\/\/)?\s*include_recursive "{{ linuxfabrik_monitoring_plugins_commands_dest_path }}"'
    line: 'include_recursive "{{ linuxfabrik_monitoring_plugins_commands_dest_path }}"'
    state: present
  notify: Reload Icinga2
