---
- name: Install LinuxFabrik Monitoring Plugins on Linux systems
  ansible.builtin.include_tasks: install-Linux.yml
  when: ansible_system == "Linux"

- name: Install LinuxFabrik Monitoring Plugins on Windows systems
  ansible.builtin.include_tasks: install-Windows.yml
  when: ansible_os_family == "Windows"
