---
- name: Remove LinuxFabrik Monitoring Plugins
  ansible.builtin.file:
    path: "{{ linuxfabrik_monitoring_plugins_dest_path }}"
    state: absent

- name: Remove the command definitions file
  ansible.builtin.file:
    path: "{{ linuxfabrik_monitoring_plugins_commands_dest_path }}/linuxfabrik-commands.conf"
    state: absent
  notify: Reload Icinga2

- name: Remove Windows command definitions on Linux system
  ansible.builtin.file:
    path: "{{ linuxfabrik_monitoring_plugins_commands_dest_path }}/windows-linuxfabrik-commands.conf"
  vars:
    linuxfabrik_monitoring_plugins_dest_path: 'C:\Program Files\ICINGA2\linuxfabrik'
  when: linuxfabrik_monitoring_plugins_install_windows_commands_on_linux
  notify: Reload Icinga2

- name: Remove the template definitions file
  ansible.builtin.file:
    path: "{{ linuxfabrik_monitoring_plugins_commands_dest_path }}/linuxfabrik-templates.conf"
  notify: Reload Icinga2

- name: Remove sudo settings
  ansible.builtin.file:
    path: /etc/sudoers.d/linuxfabrik-monitoring-plugins
    state: absent

- name: Remove the installed status file
  ansible.builtin.file:
    path: /etc/icinga2/.linuxfabrik-monitoring-plugins.installed
    state: absent
